-- Add test properties in Kentron district
INSERT INTO properties (
    title, description, property_type, transaction_type, price, currency,
    area, rooms, bedrooms, bathrooms, floor, total_floors, year_built,
    district, address, latitude, longitude, features, images, status
) VALUES 
(
    '3-комнатная квартира в центре Еревана',
    'Прекрасная квартира в самом сердце Еревана. Рядом с главными достопримечательностями, ресторанами и магазинами. Полностью меблирована, готова к заселению.',
    'apartment',
    'rent',
    350000,
    'AMD',
    85.5,
    3,
    2,
    1,
    4,
    9,
    2015,
    'Центр',
    'ул. Абовяна 23, Ереван',
    40.1823,
    44.5146,
    ARRAY['Мебель', 'Кондиционер', 'Балкон', 'Интернет', 'Парковка'],
    ARRAY['https://wse.am/img/703391dd-7309-4c1d-873e-51a4a1ee5059.jpg', 'https://wse.am/img/d6af7502-6fd6-494d-b0ff-846b279690c0.jpg'],
    'active'
),
(
    'Элитная 2-комнатная квартира на площади Республики',
    'Роскошная квартира с видом на площадь Республики. Дизайнерский ремонт, премиальная мебель, все удобства для комфортной жизни в центре столицы.',
    'apartment',
    'sale',
    180000,
    'USD',
    65.0,
    2,
    1,
    1,
    7,
    12,
    2018,
    'Центр',
    'пр. Республики 15, Ереван',
    40.1776,
    44.5126,
    ARRAY['Премиум класс', 'Вид на площадь', 'Консьерж', 'Лифт', 'Подземная парковка', 'Охрана'],
    ARRAY['https://wse.am/img/d6af7502-6fd6-494d-b0ff-846b279690c0.jpg'],
    'active'
);